import Toybox.Activity;
import Toybox.Application;
import Toybox.FitContributor;
import Toybox.Graphics;
import Toybox.Lang;
import Toybox.Math;
import Toybox.WatchUi;

// Time in Coggan power zones (%FTP) + Sweet Spot, Z4 and Z4+ totals.
//
// Time is accumulated from 1 s power while the activity timer is running
// (timer paused / auto-pause = not counted, power sensor dropout = not counted,
// 0 W while coasting = Z1). The highlighted "current zone" uses the smoothed
// power shown in the footer so it does not flicker.
class PowerZonesView extends WatchUi.DataField {

    const NUM_ZONES = 7;
    const MAX_AVG = 10;
    const STRIPE_W = 6;

    // Z1..Z7, same palette as the reference field
    var mZoneColors = [0xAAFFFF, 0x00AAFF, 0x00FF00, 0xFFFF00, 0xFFAA00, 0xFF55FF, 0xFF0000];
    const COLOR_SS = 0xFFAA00;
    const COLOR_Z4 = 0xFFFF00;
    const COLOR_Z4PLUS = 0xFF5500;

    // Settings
    var mFtp = 250;
    var mZoneMaxPct = [55, 75, 90, 105, 120, 150];
    var mZoneMaxW = new [6];
    // Sweet Spot fixed at 84-97 %FTP, both limits truncated to whole watts, inclusive
    const SS_LOW_PCT = 84;
    const SS_HIGH_PCT = 97;
    var mSsLowW = 0;
    var mSsHighW = 0;
    var mAvgN = 3;
    var mRangePct = false;
    var mLastFieldPct = false;

    // Accumulators (milliseconds)
    var mZoneMs = new [7];
    var mSsMs = 0;
    var mTotalMs = 0;
    var mLastTimer = null;

    // Live values
    var mSamples = new [10];
    var mSampleCount = 0;
    var mSampleIdx = 0;
    var mDispPower = null;
    var mCurZone = -1;
    var mInSs = false;
    var mAvgPower = null;

    // Normalized Power: 30 s rolling average, 4th power, mean, 4th root
    var mNpBuf = new [30];
    var mNpIdx = 0;
    var mNpCount = 0;
    var mNpRollSum = 0;
    var mNpSum4 = 0.0d;
    var mNpN = 0;
    var mNp = null;

    // FIT session fields (minutes)
    var mFitSs = null;
    var mFitZ4 = null;
    var mFitZ4Plus = null;

    // UI
    var mFg = Graphics.COLOR_BLACK;
    var mBg = Graphics.COLOR_WHITE;
    var mDark = false;
    var mFull = false;
    var mShowTimes = false; // bottom strip: false = NP/Avg/Pwr 3s, true = SS/Z4+/Pwr 3s
    // Bold bitmap fonts (resources/fonts, generated by tools/make_fonts.py):
    // characters "Z0123456789:%- ", capitals/digits exactly BOLD_CAP px tall,
    // drawn 1 px below the draw position.
    const BOLD_CAP = 20;
    const BOLD_SMALL_CAP = 17;
    var mBold;
    var mBoldSmall;
    // Bold bitmap fonts: zone percentages (PCT_CAP) and cell labels (LABEL_CAP)
    const PCT_CAP = 14;
    const LABEL_CAP = 14;
    var mPctFont;
    var mLabelFont;
    // Current-zone marker: arrow half-height/depth, frame line widths
    const ARROW = 9;
    const FRAME_H = 3;
    const FRAME_V = 2;
    var mFonts = [Graphics.FONT_LARGE, Graphics.FONT_MEDIUM, Graphics.FONT_SMALL, Graphics.FONT_TINY, Graphics.FONT_XTINY];

    var mStrNp;
    var mStrAvg;
    var mStrPower;
    var mStrFtp;
    var mStrSs;
    var mStrSsShort;
    var mStrZ4;
    var mStrZ4Plus;

    function initialize() {
        DataField.initialize();

        mStrNp = WatchUi.loadResource(Rez.Strings.LblNp);
        mStrAvg = WatchUi.loadResource(Rez.Strings.LblAvg);
        mStrPower = WatchUi.loadResource(Rez.Strings.LblPower);
        mStrFtp = WatchUi.loadResource(Rez.Strings.LblFtp);
        mStrSs = WatchUi.loadResource(Rez.Strings.LblSs);
        mStrSsShort = WatchUi.loadResource(Rez.Strings.LblSsShort);
        mStrZ4 = WatchUi.loadResource(Rez.Strings.LblZ4);
        mStrZ4Plus = WatchUi.loadResource(Rez.Strings.LblZ4Plus);

        mBold = WatchUi.loadResource(Rez.Fonts.Bold20);
        mBoldSmall = WatchUi.loadResource(Rez.Fonts.Bold17);
        mPctFont = WatchUi.loadResource(Rez.Fonts.Pct14);
        mLabelFont = WatchUi.loadResource(Rez.Fonts.Lbl14);

        resetTotals();
        loadSettings();
        if (DEMO_MODE > 0) {
            fillDemo();
        }

        mFitSs = createField("sweet_spot_min", 0, FitContributor.DATA_TYPE_FLOAT,
            {:mesgType => FitContributor.MESG_TYPE_SESSION, :units => "min"});
        mFitZ4 = createField("z4_min", 1, FitContributor.DATA_TYPE_FLOAT,
            {:mesgType => FitContributor.MESG_TYPE_SESSION, :units => "min"});
        mFitZ4Plus = createField("z4plus_min", 2, FitContributor.DATA_TYPE_FLOAT,
            {:mesgType => FitContributor.MESG_TYPE_SESSION, :units => "min"});
        mFitSs.setData(0.0);
        mFitZ4.setData(0.0);
        mFitZ4Plus.setData(0.0);
    }

    // ---------------------------------------------------------------- settings

    function readNum(key, def) {
        var v = null;
        try {
            v = Application.Properties.getValue(key);
        } catch (e) {
            v = null;
        }
        if (v instanceof Number) {
            return v;
        }
        if (v instanceof Float || v instanceof Double || v instanceof Long) {
            return v.toNumber();
        }
        if (v instanceof String) {
            var n = v.toNumber();
            if (n != null) {
                return n;
            }
        }
        return def;
    }

    function loadSettings() {
        mFtp = readNum("ftp", 295);
        if (mFtp < 50) {
            mFtp = 50;
        }
        var keys = ["z1Max", "z2Max", "z3Max", "z4Max", "z5Max", "z6Max"];
        var defs = [55, 75, 90, 105, 120, 150];
        var prev = 0;
        for (var i = 0; i < 6; i++) {
            var p = readNum(keys[i], defs[i]);
            if (p <= prev) {
                p = prev + 1; // keep limits strictly increasing
            }
            mZoneMaxPct[i] = p;
            mZoneMaxW[i] = (mFtp * p) / 100;
            prev = p;
        }
        mSsLowW = (mFtp * SS_LOW_PCT) / 100;
        mSsHighW = (mFtp * SS_HIGH_PCT) / 100;

        mAvgN = readNum("powerAvg", 3);
        if (mAvgN < 1) {
            mAvgN = 1;
        } else if (mAvgN > MAX_AVG) {
            mAvgN = MAX_AVG;
        }
        mSampleCount = 0;
        mSampleIdx = 0;
        mRangePct = readNum("rangeUnits", 0) == 1;
        mLastFieldPct = readNum("lastField", 0) == 1;
    }

    // ------------------------------------------------------------------ logic

    function resetTotals() {
        for (var i = 0; i < NUM_ZONES; i++) {
            mZoneMs[i] = 0;
        }
        mSsMs = 0;
        mTotalMs = 0;
        mLastTimer = null;
        mNpIdx = 0;
        mNpCount = 0;
        mNpRollSum = 0;
        mNpSum4 = 0.0d;
        mNpN = 0;
        mNp = null;
    }

    function onTimerReset() {
        resetTotals();
        updateFit();
    }

    function zoneOf(w) {
        for (var i = 0; i < 6; i++) {
            if (w <= mZoneMaxW[i]) {
                return i;
            }
        }
        return 6;
    }

    function isSs(w) {
        return w >= mSsLowW && w <= mSsHighW;
    }

    function compute(info) {
        if (DEMO_MODE > 0) {
            return; // screenshot build: keep the sample values from fillDemo()
        }
        var p = null;
        if (info has :currentPower) {
            p = info.currentPower;
        }

        // Smoothed power for display / current zone
        if (p != null) {
            mSamples[mSampleIdx] = p;
            mSampleIdx = (mSampleIdx + 1) % mAvgN;
            if (mSampleCount < mAvgN) {
                mSampleCount++;
            }
            var sum = 0;
            for (var i = 0; i < mSampleCount; i++) {
                sum += mSamples[i];
            }
            mDispPower = (sum.toFloat() / mSampleCount + 0.5).toNumber();
            mCurZone = (mDispPower > 0) ? zoneOf(mDispPower) : -1;
            mInSs = isSs(mDispPower);
        } else {
            mSampleCount = 0;
            mSampleIdx = 0;
            mDispPower = null;
            mCurZone = -1;
            mInSs = false;
        }

        mAvgPower = (info has :averagePower) ? info.averagePower : null;

        // Time accumulation driven by the activity timer (stops on pause)
        var t = info.timerTime;
        if (t == null) {
            return;
        }
        if (mLastTimer != null) {
            var dt = t - mLastTimer;
            if (dt < 0) {
                resetTotals();
            } else if (dt > 0 && dt <= 5000 && p != null) {
                // 0 W (coasting) is not time in any zone, so it does not count
                // in the zone times or in the total the percentages refer to;
                // NP still includes it, as in the standard definition
                if (p > 0) {
                    var z = zoneOf(p);
                    mZoneMs[z] += dt;
                    mTotalMs += dt;
                    if (isSs(p)) {
                        mSsMs += dt;
                    }
                }
                addNpSample(p);
                updateFit();
            }
        }
        mLastTimer = t;
    }

    // Called once per timer second with 1 s power
    function addNpSample(p) {
        if (mNpCount == 30) {
            mNpRollSum -= mNpBuf[mNpIdx];
        } else {
            mNpCount++;
        }
        mNpBuf[mNpIdx] = p;
        mNpRollSum += p;
        mNpIdx = (mNpIdx + 1) % 30;
        if (mNpCount == 30) {
            var a = mNpRollSum.toDouble() / 30.0d;
            mNpSum4 += a * a * a * a;
            mNpN++;
            mNp = (Math.pow(mNpSum4 / mNpN, 0.25) + 0.5).toNumber();
        }
    }

    // Sample values for the simulator screenshots (DEMO_MODE set by the CI)
    function fillDemo() {
        var secs = [573, 4325, 1054, 582, 69, 30, 0];
        mTotalMs = 0;
        for (var i = 0; i < NUM_ZONES; i++) {
            mZoneMs[i] = secs[i] * 1000;
            mTotalMs += mZoneMs[i];
        }
        mSsMs = 7530 * 1000; // 125:30, exercises the smaller cell font
        mNp = 241;
        mAvgPower = 230;
        mDispPower = 288;
        mCurZone = zoneOf(mDispPower);
        mInSs = isSs(mDispPower);
        mShowTimes = (DEMO_MODE == 2);
    }

    function z4PlusMs() {
        var s = 0;
        for (var i = 3; i < NUM_ZONES; i++) {
            s += mZoneMs[i];
        }
        return s;
    }

    function updateFit() {
        if (mFitSs == null) {
            return;
        }
        mFitSs.setData(mSsMs / 60000.0);
        mFitZ4.setData(mZoneMs[3] / 60000.0);
        mFitZ4Plus.setData(z4PlusMs() / 60000.0);
    }

    // -------------------------------------------------------------- formatting

    function fmtTime(ms) {
        var s = ms / 1000;
        var h = s / 3600;
        var m = (s % 3600) / 60;
        s = s % 60;
        if (h == 0) {
            return m.format("%d") + ":" + s.format("%02d");
        }
        return h.format("%d") + ":" + m.format("%02d") + ":" + s.format("%02d");
    }

    // Cells: total minutes, e.g. 1:22:30 -> "82:30"
    function fmtCellTime(ms) {
        var s = ms / 1000;
        return (s / 60).format("%d") + ":" + (s % 60).format("%02d");
    }

    function rangeText(z) {
        var a = mRangePct ? mZoneMaxPct : mZoneMaxW;
        var u = mRangePct ? "%" : "W";
        if (z == 0) {
            return (mRangePct ? "0" : "1") + " - " + a[0].toString() + u;
        } else if (z == 6) {
            return "> " + a[5].toString() + u;
        }
        return (a[z - 1] + 1).toString() + " - " + a[z].toString() + u;
    }

    // Digits and ':' only: safe to draw with the large number fonts
    function isNumeric(text) {
        var chars = text.toCharArray();
        for (var i = 0; i < chars.size(); i++) {
            var c = chars[i].toNumber();
            // digits, ':', '%', '-', ' ' (the characters of the bold fonts)
            if (!((c >= 48 && c <= 58) || c == 37 || c == 45 || c == 32)) {
                return false;
            }
        }
        return chars.size() > 0;
    }

    // Largest font whose height fits maxH (and text fits maxW when given)
    function pickFont(dc, text, maxW, maxH) {
        for (var i = 0; i < mFonts.size(); i++) {
            var f = mFonts[i];
            if (dc.getFontHeight(f) <= maxH &&
                (text == null || dc.getTextWidthInPixels(text, f) <= maxW)) {
                return f;
            }
        }
        return Graphics.FONT_XTINY;
    }

    // ------------------------------------------------------------------ drawing

    // System font metrics, measured per device in the simulator
    // (metrics/*/FontMetrics.mc, selected by monkey.jungle)
    var mSysFonts = [Graphics.FONT_XTINY, Graphics.FONT_TINY, Graphics.FONT_SMALL,
                     Graphics.FONT_MEDIUM, Graphics.FONT_LARGE];

    function fontIdx(f) {
        for (var i = 0; i < mSysFonts.size(); i++) {
            if (mSysFonts[i] == f) {
                return i;
            }
        }
        return 0;
    }

    function fontCap(dc, f) {
        return fontCapPx(fontIdx(f));
    }

    // Largest system font whose capitals are at most `cap` px (scaled from
    // the 322 px tall Edge 830/840 screen), XTINY if none
    function fontForCap(dc, cap) {
        var target = (cap * dc.getHeight()) / 322;
        var best = Graphics.FONT_XTINY;
        for (var i = 0; i < mSysFonts.size(); i++) {
            if (fontCapPx(i) <= target) {
                best = mSysFonts[i];
            }
        }
        return best;
    }

    // Draw text with the bottom of its capitals/digits at yb
    function drawBase(dc, x, yb, f, text, just) {
        var i = fontIdx(f);
        dc.drawText(x, yb - fontCapPx(i) - fontTopPx(i), f, text, just);
    }

    // Draw with a bold font so that the top of the capitals is at yTop
    function drawBold(dc, x, yTop, f, text, just) {
        dc.drawText(x, yTop - 1, f, text, just);
    }

    function onUpdate(dc) {
        var w = dc.getWidth();
        var h = dc.getHeight();

        mBg = getBackgroundColor();
        mDark = (mBg == Graphics.COLOR_BLACK);
        mFg = mDark ? Graphics.COLOR_WHITE : Graphics.COLOR_BLACK;
        dc.setColor(mFg, mBg);
        dc.clear();

        if (DEMO_MODE == 3) {
            drawCalibration(dc);
            return;
        }

        mFull = (h >= 240);
        if (mFull) {
            // Full page: 7 two-line zone rows + one strip of 3 cells (tap toggles the set)
            var stripH = cellHeight(dc);
            var rowH = (h - stripH) / NUM_ZONES;
            var zonesH = rowH * NUM_ZONES;
            for (var j = 0; j < NUM_ZONES; j++) {
                drawZoneRow(dc, NUM_ZONES - 1 - j, 0, j * rowH, w, rowH);
            }
            if (mShowTimes) {
                drawSummary(dc, 0, zonesH, w, h - zonesH);
            } else {
                drawFooter(dc, 0, zonesH, w, h - zonesH);
            }
        } else if (h >= 90) {
            var half = h / 2;
            drawSummary(dc, 0, 0, w, half);
            drawFooter(dc, 0, half, w, h - half);
        } else {
            drawSummary(dc, 0, 0, w, h);
        }
    }

    // Calibration screen for the CI: each system font drawn at a known y
    // (red line) next to its getFontHeight(), analysed from the screenshot
    function drawCalibration(dc) {
        var fonts = [Graphics.FONT_XTINY, Graphics.FONT_TINY, Graphics.FONT_SMALL,
                     Graphics.FONT_MEDIUM, Graphics.FONT_LARGE];
        dc.setColor(Graphics.COLOR_WHITE, Graphics.COLOR_WHITE);
        dc.clear();
        for (var i = 0; i < fonts.size(); i++) {
            var y = 10 + i * 60;
            dc.setColor(Graphics.COLOR_RED, Graphics.COLOR_TRANSPARENT);
            dc.drawLine(0, y, 20, y);
            dc.setColor(Graphics.COLOR_BLACK, Graphics.COLOR_TRANSPARENT);
            dc.drawText(30, y, fonts[i], "8Z", Graphics.TEXT_JUSTIFY_LEFT);
            dc.drawText(150, y, Graphics.FONT_XTINY, dc.getFontHeight(fonts[i]).toString(), Graphics.TEXT_JUSTIFY_LEFT);
        }
    }

    // Called by PowerZonesDelegate on a tap inside the field
    function onFieldTap() {
        if (!mFull) {
            return false;
        }
        mShowTimes = !mShowTimes;
        WatchUi.requestUpdate();
        return true;
    }

    // Cell: 3 px + label + 5 px + value (bold) + 5 px
    function cellHeight(dc) {
        return 3 + LABEL_CAP + 5 + BOLD_CAP + 5;
    }

    function drawZoneRow(dc, z, x, y, w, rh) {
        var col = mZoneColors[z];
        var ms = mZoneMs[z];
        var frac = mTotalMs > 0 ? ms.toFloat() / mTotalMs : 0.0;
        var inner = w - STRIPE_W;

        dc.setColor(col, col);
        dc.fillRectangle(x, y, STRIPE_W, rh);
        var barW = (inner * frac).toNumber();
        if (barW > 0) {
            if (mDark) {
                // thin bar keeps white text readable on black
                dc.fillRectangle(x + STRIPE_W, y + rh - 5, barW, 4);
            } else {
                dc.fillRectangle(x + STRIPE_W, y + 1, barW, rh - 2);
            }
        }

        var label = "Z" + (z + 1);
        var timeStr = ms > 0 ? fmtTime(ms) : "";
        var pctStr = mTotalMs > 0 ? (frac * 100 + 0.5).toNumber().toString() + "%" : "";
        var range = rangeText(z);
        // clear of the current-zone arrows (ARROW px deep) on both sides
        var tx = x + 1 + ARROW + 9;
        var right = x + w - 2 - ARROW - 5;

        // Two lines, like the reference field:
        //   "Z3   12:34"   bold, capitals BOLD_CAP px (BOLD_SMALL_CAP if the row is short)
        //   "224 - 268W"   XTINY
        // The percentage (TINY) sits on the right, vertically centred.
        var sf = Graphics.FONT_XTINY;
        var capS = fontCap(dc, sf);
        var smallBase = y + rh - 3;
        var bf = mBold;
        var cap = BOLD_CAP;
        if (cap + capS + 9 > rh) {
            bf = mBoldSmall;
            cap = BOLD_SMALL_CAP;
        }
        var topY = smallBase - capS - 4 - cap;
        if (topY < y + 2) {
            topY = y + 2;
        }

        dc.setColor(mFg, Graphics.COLOR_TRANSPARENT);
        drawBold(dc, tx, topY, bf, label, Graphics.TEXT_JUSTIFY_LEFT);
        if (timeStr.length() > 0) {
            // keep clear of the percentage: long times (> 1 h) may need the smaller bold font
            var timeX = tx + dc.getTextWidthInPixels(label, bf) + 14;
            var maxRight = right - dc.getTextWidthInPixels("100%", mPctFont) - 8;
            var tf = bf;
            var tTop = topY;
            if (timeX + dc.getTextWidthInPixels(timeStr, tf) > maxRight) {
                tf = mBoldSmall;
                tTop = topY + (cap - BOLD_SMALL_CAP);
            }
            drawBold(dc, timeX, tTop, tf, timeStr, Graphics.TEXT_JUSTIFY_LEFT);
        }
        drawBase(dc, tx, smallBase, sf, range, Graphics.TEXT_JUSTIFY_LEFT);

        var pctTop = y + (rh - PCT_CAP) / 2;
        if (pctStr.length() > 0) {
            drawBold(dc, right, pctTop, mPctFont, pctStr, Graphics.TEXT_JUSTIFY_RIGHT);
        } else if (z == 6) {
            // Before the first second of data, show which build is installed
            drawBase(dc, right, pctTop + PCT_CAP, sf, "build " + BUILD_NUMBER, Graphics.TEXT_JUSTIFY_RIGHT);
        }

        if (z == mCurZone) {
            drawCurrentMarker(dc, z, x, y, w, rh);
        }
    }

    // Box around the current zone; the two arrows move vertically with the
    // power inside the zone: bottom = lower limit, top = upper limit
    // (Z1 starts at 0 W, Z7 ends at 200% FTP; outside the arrows stay at the edge).
    function drawCurrentMarker(dc, z, x, y, w, rh) {
        drawFrame(dc, x + 1, y, w - 2, rh);

        var lo = (z == 0) ? 1 : mZoneMaxW[z - 1] + 1;
        var hi = (z == 6) ? (mFtp * 2) : mZoneMaxW[z];
        var f = 0.5;
        if (mDispPower != null && hi > lo) {
            f = (mDispPower - lo).toFloat() / (hi - lo);
            if (f < 0.0) {
                f = 0.0;
            } else if (f > 1.0) {
                f = 1.0;
            }
        }
        var a = ARROW;
        if (a > rh / 3) {
            a = rh / 3;
        }
        var top = y + FRAME_H + a;
        var bottom = y + rh - 1 - FRAME_H - a;
        var cy = bottom - ((bottom - top) * f).toNumber();
        dc.fillPolygon([[x + 1, cy - a], [x + 1 + a, cy], [x + 1, cy + a]]);
        dc.fillPolygon([[x + w - 2, cy - a], [x + w - 2 - a, cy], [x + w - 2, cy + a]]);
    }

    // Frame of the current zone / active cell: horizontal lines FRAME_H px,
    // vertical lines FRAME_V px, drawn inside the given rectangle
    function drawFrame(dc, x, y, w, h) {
        dc.setColor(mFg, Graphics.COLOR_TRANSPARENT);
        dc.fillRectangle(x, y, w, FRAME_H);
        dc.fillRectangle(x, y + h - FRAME_H, w, FRAME_H);
        dc.fillRectangle(x, y, FRAME_V, h);
        dc.fillRectangle(x + w - FRAME_V, y, FRAME_V, h);
    }

    // Second set (tap): SS / Z4+ / Pwr 3s
    function drawSummary(dc, x, y, w, h) {
        var cw = w / 3;
        // never filled: the active one gets the same frame as the current zone
        drawCell(dc, x, y, cw, h, "SS", fmtCellTime(mSsMs), null);
        if (mInSs) {
            drawFrame(dc, x, y, cw, h);
        }
        drawCell(dc, x + cw, y, cw, h, "Z4+", fmtCellTime(z4PlusMs()), null);
        if (mCurZone >= 3) {
            drawFrame(dc, x + cw, y, cw, h);
        }
        drawPowerCell(dc, x + 2 * cw, y, w - 2 * cw, h);
    }

    function drawFooter(dc, x, y, w, h) {
        var cw = w / 3;
        drawCell(dc, x, y, cw, h, "NP", mNp != null ? mNp.toString() : "--", null);
        drawCell(dc, x + cw, y, cw, h, "AVG", mAvgPower != null ? mAvgPower.toString() : "--", null);

        drawPowerCell(dc, x + 2 * cw, y, w - 2 * cw, h);
    }

    // Smoothed power (or %FTP), coloured like the current zone; used by both sets
    function drawPowerCell(dc, x, y, cw, h) {
        var label = (mLastFieldPct ? "%" : "W") + " " + mAvgN.toString() + "s";
        var val = "--";
        if (mDispPower != null) {
            val = mLastFieldPct
                ? ((mDispPower * 100.0 / mFtp) + 0.5).toNumber().toString() + "%"
                : mDispPower.toString();
        }
        drawCell(dc, x, y, cw, h, label, val, mCurZone >= 0 ? mZoneColors[mCurZone] : null);
    }

    function drawCell(dc, x, y, cw, ch, label, value, hl) {
        var fg = mFg;
        if (hl != null) {
            dc.setColor(hl, hl);
            dc.fillRectangle(x, y, cw, ch);
            fg = Graphics.COLOR_BLACK;
        }
        var cx = x + cw / 2;
        dc.setColor(fg, Graphics.COLOR_TRANSPARENT);

        // Label: regular LABEL_CAP px font, capitals 3 px from the top
        drawBold(dc, cx, y + 3, mLabelFont, label, Graphics.TEXT_JUSTIFY_CENTER);

        // Value: same bold font in every cell; only a value that does not fit
        // (e.g. more than 100 minutes) uses the slightly smaller one
        if (isNumeric(value) && dc.getTextWidthInPixels(value, mBold) <= cw - 4) {
            drawBold(dc, cx, y + ch - 5 - BOLD_CAP, mBold, value, Graphics.TEXT_JUSTIFY_CENTER);
        } else if (isNumeric(value) && dc.getTextWidthInPixels(value, mBoldSmall) <= cw - 4) {
            drawBold(dc, cx, y + ch - 5 - BOLD_SMALL_CAP, mBoldSmall, value, Graphics.TEXT_JUSTIFY_CENTER);
        } else {
            drawBase(dc, cx, y + ch - 5, Graphics.FONT_SMALL, value, Graphics.TEXT_JUSTIFY_CENTER);
        }

        dc.setColor(mFg, Graphics.COLOR_TRANSPARENT);
        dc.drawRectangle(x, y, cw, ch);
    }
}
